version: "3.8"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTORCH_URL: ${PYTORCH_URL}
    volumes:
      - "${JUPYTER_VOLUME_PATH}:/home/jovyan/work"
    ports:
      - "8403:8888"
    command: "start-notebook.sh --IdentityProvider.token='${TOKEN}'"
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]